// <auto-generated />
using System;
using Furni101.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Furni101.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Furni101.Models.BLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("bLogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmployeeId = 2,
                            ImageUrl = "post-1.jpg",
                            Text = "ASP.NET Core ",
                            Title = "ASP.NET Core "
                        },
                        new
                        {
                            Id = 2,
                            EmployeeId = 3,
                            ImageUrl = "post-2.jpg",
                            Text = "Entity Framework Core",
                            Title = "Entity Framework Core "
                        },
                        new
                        {
                            Id = 3,
                            EmployeeId = 1,
                            ImageUrl = "post-3.jpg",
                            Text = "Temiz kod, okunabilirliği artırır ve bakım maliyetlerini düşürür.",
                            Title = "Clean Code Yazmanın Önemi"
                        });
                });

            modelBuilder.Entity("Furni101.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2025, 12, 29, 8, 17, 13, 502, DateTimeKind.Local).AddTicks(5250),
                            Description = "Backend developer",
                            FirstName = "Ahmet",
                            ImageUrl = "person_1.jpg",
                            LastName = "Yılmaz",
                            Position = "Software Developer",
                            UpdateDate = new DateTime(2025, 12, 29, 8, 17, 13, 502, DateTimeKind.Local).AddTicks(5261)
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2025, 12, 29, 8, 17, 13, 502, DateTimeKind.Local).AddTicks(5264),
                            Description = "Frontend designer",
                            FirstName = "Ayşe",
                            ImageUrl = "person_2.jpg",
                            LastName = "Kaya",
                            Position = "UI/UX Designer",
                            UpdateDate = new DateTime(2025, 12, 29, 8, 17, 13, 502, DateTimeKind.Local).AddTicks(5265)
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2025, 12, 29, 8, 17, 13, 502, DateTimeKind.Local).AddTicks(5266),
                            Description = "Team lead",
                            FirstName = "Mehmet",
                            ImageUrl = "person_3.jpg",
                            LastName = "Demir",
                            Position = "Project Manager",
                            UpdateDate = new DateTime(2025, 12, 29, 8, 17, 13, 502, DateTimeKind.Local).AddTicks(5267)
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2025, 12, 29, 8, 17, 13, 502, DateTimeKind.Local).AddTicks(5268),
                            Description = "Testing specialist",
                            FirstName = "Elif",
                            ImageUrl = "person_4.jpg",
                            LastName = "Çelik",
                            Position = "QA Engineer",
                            UpdateDate = new DateTime(2025, 12, 29, 8, 17, 13, 502, DateTimeKind.Local).AddTicks(5268)
                        });
                });

            modelBuilder.Entity("Furni101.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageName = "product-1",
                            ImageUrl = "product-1.png",
                            IsDeleted = false,
                            Name = "Product 1",
                            Price = 50.0,
                            UpdateDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageName = "product-2",
                            ImageUrl = "product-2.png",
                            IsDeleted = false,
                            Name = "Product 2",
                            Price = 75.0,
                            UpdateDate = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageName = "product-3",
                            ImageUrl = "product-3.png",
                            IsDeleted = false,
                            Name = "Product 3",
                            Price = 120.0,
                            UpdateDate = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2024, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageName = "product-1",
                            ImageUrl = "product-1.png",
                            IsDeleted = false,
                            Name = "Product 4",
                            Price = 60.0,
                            UpdateDate = new DateTime(2024, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CreateDate = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageName = "product-2",
                            ImageUrl = "product-2.png",
                            IsDeleted = false,
                            Name = "Product 5",
                            Price = 90.0,
                            UpdateDate = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            CreateDate = new DateTime(2024, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageName = "product-3",
                            ImageUrl = "product-3.png",
                            IsDeleted = false,
                            Name = "Product 6",
                            Price = 150.0,
                            UpdateDate = new DateTime(2024, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            CreateDate = new DateTime(2024, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageName = "product-1",
                            ImageUrl = "product-1.png",
                            IsDeleted = false,
                            Name = "Product 7",
                            Price = 110.0,
                            UpdateDate = new DateTime(2024, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            CreateDate = new DateTime(2024, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageName = "product-2",
                            ImageUrl = "product-2.png",
                            IsDeleted = false,
                            Name = "Product 8",
                            Price = 200.0,
                            UpdateDate = new DateTime(2024, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Furni101.Models.BLog", b =>
                {
                    b.HasOne("Furni101.Models.Employee", "Employee")
                        .WithMany("Blogs")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Furni101.Models.Employee", b =>
                {
                    b.Navigation("Blogs");
                });
#pragma warning restore 612, 618
        }
    }
}
